# Site settings
title: A little bit about me

description: > # this means to ignore newlines until "baseurl:"
  a little description about me

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://itshenry.com" # the base hostname & protocol for your site

twitter_username: mathphysicsflow

github_username:  hsavit1

# Build settings
markdown: kramdown
