# Site settings
title: Henry's Moment of Zen

description: > # this means to ignore newlines until "baseurl:"
  thoughts and thought experiments. zen for the soul

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://itshenry.com" # the base hostname & protocol for your site

twitter_username: hsavit1

github_username:  hsavit1

email: henrysavit@gmail.com

# Build settings
markdown: kramdown

gems:
  - jemoji